### ISSUE TITLE
[FEATURE] Parsing the message key inside error.data object

### ISSUE THREAD

**Issue by spandansingh** [enzoferey/ethers-error-parser#7]
Should be able to parse the exact reason from the `message` key which is inside the `error.data` object.

This message is the reason for transaction failure often written inside the **_require_** function of smart contracts.

**Comment by enzoferey** [comment]
Hi @spandansingh !

Thanks for pointing it out, do you have any example for such error ? That will make things easier for me to reproduce and cover 👌🏻 

> This message is the reason for transaction failure often written inside the require function of smart contracts.

From my experience this is usually included inside the `error.error.message` key. I believe the `EXECUTION_REVERTED` error code is handling reverts because of a `require` Solidity statement. I might be wrong though.

**Comment by spandansingh** [comment]
Hi @enzoferey 

Love what you are doing here mate!! ❤️ ❤️ 

Please find an example of such an error:

```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: Staking in this pool is concluded", method="estimateGas", transaction={"from":"0x8777D52c3AE17eC694f24f75Adf537c8F4F98B72","to":"0x3aB1568A1719d521281A4C34b4Cc123436fe846e","data":"0x7b0472f00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000e8d4a51000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted: Staking in this pool is concluded","data":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000215374616b696e6720696e207468697320706f6f6c20697320636f6e636c7564656400000000000000000000000000000000000000000000000000000000000000"},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": 3,\n    \"message\": \"execution reverted: Staking in this pool is concluded\",\n    \"data\": \"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000215374616b696e6720696e207468697320706f6f6c20697320636f6e636c7564656400000000000000000000000000000000000000000000000000000000000000\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:308657)\\n    at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:311413)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:312023)\\n    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:3:101606)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:3:102638\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:3412\"\n}\n  at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:308657)\n  at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:311413)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:312023)\n  at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:3:101606)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:3:102638\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:3412"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.6.8)
    at Logger.makeError (index.ts:261:1)
    at Logger.throwError (index.ts:273:1)
    at checkError (json-rpc-provider.ts:78:1)
    at Web3Provider.<anonymous> (json-rpc-provider.ts:603:1)
    at Generator.throw (<anonymous>)
    at rejected (json-rpc-provider.ts:2:1)
```

This is the output of `console.log(error)` in which the exact reason is `execution reverted: Staking in this pool is concluded` 

` Staking in this pool is concluded` has been written inside the `require` solidity.

I guess its inside `error.error.data.message`

**Comment by enzoferey** [comment]
Awesome @spandansingh, that's very helpful 🙌🏻 

I will have a look at this error stack and work on supporting it 👍🏻

**Comment by enzoferey** [comment]
@spandansingh This feature is now supported on version `0.2.0` => https://www.npmjs.com/package/@enzoferey/ethers-error-parser/v/0.2.0
